# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WTemplateInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'description': 'str',
        'fields': 'list[TemplateFieldInfo]',
        'color': 'OneOfWTemplateInfoColor',
        'field_count': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'fields': 'fields',
        'color': 'color',
        'field_count': 'fieldCount'
    }

    def __init__(self, id=None, name=None, description=None, fields=None, color=None, field_count=None):  # noqa: E501
        """WTemplateInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._description = None
        self._fields = None
        self._color = None
        self._field_count = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if fields is not None:
            self.fields = fields
        if color is not None:
            self.color = color
        if field_count is not None:
            self.field_count = field_count

    @property
    def id(self):
        """Gets the id of this WTemplateInfo.  # noqa: E501

        The ID of the template definition.  # noqa: E501

        :return: The id of this WTemplateInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WTemplateInfo.

        The ID of the template definition.  # noqa: E501

        :param id: The id of this WTemplateInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this WTemplateInfo.  # noqa: E501

        The name of the template definition.  # noqa: E501

        :return: The name of this WTemplateInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WTemplateInfo.

        The name of the template definition.  # noqa: E501

        :param name: The name of this WTemplateInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this WTemplateInfo.  # noqa: E501

        The description of the template definition.  # noqa: E501

        :return: The description of this WTemplateInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this WTemplateInfo.

        The description of the template definition.  # noqa: E501

        :param description: The description of this WTemplateInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def fields(self):
        """Gets the fields of this WTemplateInfo.  # noqa: E501

        A list of template fields which are assigned to the template.  # noqa: E501

        :return: The fields of this WTemplateInfo.  # noqa: E501
        :rtype: list[TemplateFieldInfo]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this WTemplateInfo.

        A list of template fields which are assigned to the template.  # noqa: E501

        :param fields: The fields of this WTemplateInfo.  # noqa: E501
        :type: list[TemplateFieldInfo]
        """

        self._fields = fields

    @property
    def color(self):
        """Gets the color of this WTemplateInfo.  # noqa: E501

        The color assigned to the template definition.  # noqa: E501

        :return: The color of this WTemplateInfo.  # noqa: E501
        :rtype: OneOfWTemplateInfoColor
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this WTemplateInfo.

        The color assigned to the template definition.  # noqa: E501

        :param color: The color of this WTemplateInfo.  # noqa: E501
        :type: OneOfWTemplateInfoColor
        """

        self._color = color

    @property
    def field_count(self):
        """Gets the field_count of this WTemplateInfo.  # noqa: E501

        The number of fields assigned to the template.  # noqa: E501

        :return: The field_count of this WTemplateInfo.  # noqa: E501
        :rtype: int
        """
        return self._field_count

    @field_count.setter
    def field_count(self, field_count):
        """Sets the field_count of this WTemplateInfo.

        The number of fields assigned to the template.  # noqa: E501

        :param field_count: The field_count of this WTemplateInfo.  # noqa: E501
        :type: int
        """

        self._field_count = field_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WTemplateInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WTemplateInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
