# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import laserfiche-api
from laserfiche-api.api.simple_searches_api import SimpleSearchesApi  # noqa: E501
from laserfiche-api.rest import ApiException


class TestSimpleSearchesApi(unittest.TestCase):
    """SimpleSearchesApi unit test stubs"""

    def setUp(self):
        self.api = SimpleSearchesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_simple_search_operation(self):
        """Test case for create_simple_search_operation

        """
        pass


if __name__ == '__main__':
    unittest.main()
