# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import laserfiche-api
from laserfiche-api.models.copy_async_request import CopyAsyncRequest  # noqa: E501
from laserfiche-api.rest import ApiException


class TestCopyAsyncRequest(unittest.TestCase):
    """CopyAsyncRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCopyAsyncRequest(self):
        """Test CopyAsyncRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = laserfiche-api.models.copy_async_request.CopyAsyncRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
