# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import laserfiche-api
from laserfiche-api.api.searches_api import SearchesApi  # noqa: E501
from laserfiche-api.rest import ApiException


class TestSearchesApi(unittest.TestCase):
    """SearchesApi unit test stubs"""

    def setUp(self):
        self.api = SearchesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_or_close_a_search(self):
        """Test case for cancel_or_close_a_search

        Cancel or close an advanced search.  # noqa: E501
        """
        pass

    def test_create_search_operation(self):
        """Test case for create_search_operation

        Run a search in the specified repository.  # noqa: E501
        """
        pass

    def test_get_search_context_hits(self):
        """Test case for get_search_context_hits

        """
        pass

    def test_get_search_results(self):
        """Test case for get_search_results

        Get the search results listing of a search.  # noqa: E501
        """
        pass

    def test_get_search_status(self):
        """Test case for get_search_status

        Get the status of a search using a token.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
