# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import laserfiche-api
from laserfiche-api.api.entries_api import EntriesApi  # noqa: E501
from laserfiche-api.rest import ApiException


class TestEntriesApi(unittest.TestCase):
    """EntriesApi unit test stubs"""

    def setUp(self):
        self.api = EntriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_entry_links(self):
        """Test case for assign_entry_links

        """
        pass

    def test_assign_field_values(self):
        """Test case for assign_field_values

        """
        pass

    def test_assign_tags(self):
        """Test case for assign_tags

        """
        pass

    def test_copy_entry_async(self):
        """Test case for copy_entry_async

        """
        pass

    def test_create_or_copy_entry(self):
        """Test case for create_or_copy_entry

        """
        pass

    def test_delete_assigned_template(self):
        """Test case for delete_assigned_template

        """
        pass

    def test_delete_entry_info(self):
        """Test case for delete_entry_info

        """
        pass

    def test_export_document(self):
        """Test case for export_document

        """
        pass

    def test_export_document_with_audit_reason(self):
        """Test case for export_document_with_audit_reason

        """
        pass

    def test_get_document_content_type(self):
        """Test case for get_document_content_type

        """
        pass

    def test_get_dynamic_field_values(self):
        """Test case for get_dynamic_field_values

        """
        pass

    def test_get_entry(self):
        """Test case for get_entry

        """
        pass

    def test_get_entry_listing(self):
        """Test case for get_entry_listing

        """
        pass

    def test_get_field_values(self):
        """Test case for get_field_values

        """
        pass

    def test_get_link_values_from_entry(self):
        """Test case for get_link_values_from_entry

        """
        pass

    def test_get_tags_assigned_to_entry(self):
        """Test case for get_tags_assigned_to_entry

        """
        pass

    def test_import_document(self):
        """Test case for import_document

        """
        pass

    def test_move_or_rename_document(self):
        """Test case for move_or_rename_document

        """
        pass

    def test_write_template_value_to_entry(self):
        """Test case for write_template_value_to_entry

        """
        pass


if __name__ == '__main__':
    unittest.main()
