# coding: utf-8

"""
    Laserfiche API

    Welcome to the Laserfiche API Swagger Playground. You can try out any of our API calls against your live Laserfiche Cloud account. Visit the developer center for more details: <a href=\"https://developer.laserfiche.com\">https://developer.laserfiche.com</a><p><strong>Build# : </strong>561590</p>  # noqa: E501

    OpenAPI spec version: 1-alpha
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import laserfiche-api
from laserfiche-api.models.one_of_advanced_search_request_fuzzy_type import OneOfAdvancedSearchRequestFuzzyType  # noqa: E501
from laserfiche-api.rest import ApiException


class TestOneOfAdvancedSearchRequestFuzzyType(unittest.TestCase):
    """OneOfAdvancedSearchRequestFuzzyType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfAdvancedSearchRequestFuzzyType(self):
        """Test OneOfAdvancedSearchRequestFuzzyType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = laserfiche-api.models.one_of_advanced_search_request_fuzzy_type.OneOfAdvancedSearchRequestFuzzyType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
